Update pythonlocation.yml

diff --git a/.github/workflows/pythonlocation.yml b/.github/workflows/pythonlocation.yml
--- a/.github/workflows/pythonlocation.yml
+++ b/.github/workflows/pythonlocation.yml
@@ -10,7 +10,7 @@ jobs:
       fail-fast: false
       matrix:
           runners: ['ubuntu-latest','windows-latest','macos-13','macos-latest']
-          python-version: [ '3.11', 'pypy3.10', 'graalpy-24.0', '3.13t', 'invalid' ]
+          python-version: [ '3.11', 'pypy3.10', 'graalpy-24', '3.13t', 'invalid' ]
     steps:
       - uses: actions/checkout@v4
       - name: Set up ${{ matrix.python-version }}
@@ -43,11 +43,34 @@ jobs:
           }
           & "$env:pythonLocation\python.exe" --version
 
-      - name: Negative test - expect failure for invalid pythonImplementation
-        continue-on-error: true
+      - name: Check Python executable layout
+        shell: bash
         run: |
-          echo "This combination should fail to set up Python."
-
-
-            echo "Failure as expected for invalid config."
+          echo "pythonLocation: $pythonLocation"
+          if [[ "${{ matrix.python-version }}" != "pypy3.10" && "${{ matrix.python-implementation }}" != "graalpy-24" ]]; then
+            # On Windows, the executable will be python.exe
+            if [[ "$RUNNER_OS" == "Windows" ]]; then
+              if [ ! -f "$pythonLocation/python.exe" ]; then
+                echo "::error ::CPython should have python.exe at root of pythonLocation"
+                exit 1
+              fi
+            else
+              if [ ! -f "$pythonLocation/bin/python" ] && [ ! -f "$pythonLocation/python" ]; then
+                echo "::error ::CPython should have python or python binary at root/bin of pythonLocation"
+                exit 1
+              fi
+            fi
+          else
+            # PyPy and GraalPy should NOT have python executable at the root
+            if [[ "$RUNNER_OS" == "Windows" ]]; then
+              if [ -f "$pythonLocation/python.exe" ]; then
+                echo "::error ::PyPy/GraalPy should NOT have python.exe at root of pythonLocation"
+                exit 1
+              fi
+            else
+              if [ -f "$pythonLocation/bin/python" ] || [ -f "$pythonLocation/python" ]; then
+                echo "::error ::PyPy/GraalPy should NOT have python or python binary at root/bin of pythonLocation"
+                exit 1
+              fi
+            fi
           fi
